// setter logic - generated by gen_verilog.go

        `OFFSET_TrigSource                      : trig_source                    <= wdata[32-1: 0];
        `OFFSET_NumSamp                         : num_samp                       <= wdata[32-1: 0];
        `OFFSET_DecRate                         : dec_rate                       <= wdata[32-1: 0];
        `OFFSET_Options                         : options                        <= wdata[32-1: 0];
        `OFFSET_TrigThreshExcite                : trig_thresh_excite             <= wdata[32-1: 0];
        `OFFSET_TrigThreshRelax                 : trig_thresh_relax              <= wdata[32-1: 0];
        `OFFSET_TrigDelay                       : trig_delay                     <= wdata[32-1: 0];
        `OFFSET_TrigLatency                     : trig_latency                   <= wdata[32-1: 0];
        `OFFSET_ACPThreshExcite                 : acp_thresh_excite              <= wdata[32-1: 0];
        `OFFSET_ACPThreshRelax                  : acp_thresh_relax               <= wdata[32-1: 0];
        `OFFSET_ACPLatency                      : acp_latency                    <= wdata[32-1: 0];
        `OFFSET_ARPThreshExcite                 : arp_thresh_excite              <= wdata[32-1: 0];
        `OFFSET_ARPThreshRelax                  : arp_thresh_relax               <= wdata[32-1: 0];
        `OFFSET_ARPLatency                      : arp_thresh_latency             <= wdata[32-1: 0];
