// getter logic - generated by ogdar.go

        `OFFSET_TrigSource                 : begin ack <= 1'b1;  rdata <= trig_source                   [32-1: 0]; end
        `OFFSET_NumSamp                    : begin ack <= 1'b1;  rdata <= num_samp                      [32-1: 0]; end
        `OFFSET_DecRate                    : begin ack <= 1'b1;  rdata <= dec_rate                      [32-1: 0]; end
        `OFFSET_Options                    : begin ack <= 1'b1;  rdata <= options                       [32-1: 0]; end
        `OFFSET_TrigThreshExcite           : begin ack <= 1'b1;  rdata <= trig_thresh_excite            [32-1: 0]; end
        `OFFSET_TrigThreshRelax            : begin ack <= 1'b1;  rdata <= trig_thresh_relax             [32-1: 0]; end
        `OFFSET_TrigDelay                  : begin ack <= 1'b1;  rdata <= trig_delay                    [32-1: 0]; end
        `OFFSET_TrigLatency                : begin ack <= 1'b1;  rdata <= trig_latency                  [32-1: 0]; end
        `OFFSET_ACPThreshExcite            : begin ack <= 1'b1;  rdata <= acp_thresh_excite             [32-1: 0]; end
        `OFFSET_ACPThreshRelax             : begin ack <= 1'b1;  rdata <= acp_thresh_relax              [32-1: 0]; end
        `OFFSET_ACPLatency                 : begin ack <= 1'b1;  rdata <= acp_latency                   [32-1: 0]; end
        `OFFSET_ARPThreshExcite            : begin ack <= 1'b1;  rdata <= arp_thresh_excite             [32-1: 0]; end
        `OFFSET_ARPThreshRelax             : begin ack <= 1'b1;  rdata <= arp_thresh_relax              [32-1: 0]; end
        `OFFSET_ARPLatency                 : begin ack <= 1'b1;  rdata <= arp_thresh_latency            [32-1: 0]; end
        `OFFSET_TrigClock_LO               : begin ack <= 1'b1;  rdata <= trig_clock                    [32-1: 0]; end
        `OFFSET_TrigClock_HI               : begin ack <= 1'b1;  rdata <= trig_clock                    [64-1:32]; end
        `OFFSET_TrigPrevClock_LO           : begin ack <= 1'b1;  rdata <= trig_prev_clock               [32-1: 0]; end
        `OFFSET_TrigPrevClock_HI           : begin ack <= 1'b1;  rdata <= trig_prev_clock               [64-1:32]; end
        `OFFSET_ACPClock_LO                : begin ack <= 1'b1;  rdata <= acp_clock                     [32-1: 0]; end
        `OFFSET_ACPClock_HI                : begin ack <= 1'b1;  rdata <= acp_clock                     [64-1:32]; end
        `OFFSET_ACPPrevClock_LO            : begin ack <= 1'b1;  rdata <= acp_prev_clock                [32-1: 0]; end
        `OFFSET_ACPPrevClock_HI            : begin ack <= 1'b1;  rdata <= acp_prev_clock                [64-1:32]; end
        `OFFSET_ARPClock_LO                : begin ack <= 1'b1;  rdata <= arp_clock                     [32-1: 0]; end
        `OFFSET_ARPClock_HI                : begin ack <= 1'b1;  rdata <= arp_clock                     [64-1:32]; end
        `OFFSET_ARPPrevClock_LO            : begin ack <= 1'b1;  rdata <= arp_prev_clock                [32-1: 0]; end
        `OFFSET_ARPPrevClock_HI            : begin ack <= 1'b1;  rdata <= arp_prev_clock                [64-1:32]; end
        `OFFSET_TrigCount                  : begin ack <= 1'b1;  rdata <= trig_count                    [32-1: 0]; end
        `OFFSET_ACPCount                   : begin ack <= 1'b1;  rdata <= acp_count                     [32-1: 0]; end
        `OFFSET_ARPCount                   : begin ack <= 1'b1;  rdata <= arp_count                     [32-1: 0]; end
        `OFFSET_ACPPerARP                  : begin ack <= 1'b1;  rdata <= acp_per_arp                   [32-1: 0]; end
        `OFFSET_ADCCounter                 : begin ack <= 1'b1;  rdata <= adc_counter                   [32-1: 0]; end
        `OFFSET_ACPAtARP                   : begin ack <= 1'b1;  rdata <= acp_at_arp                    [32-1: 0]; end
        `OFFSET_ClockSinceACPAtARP         : begin ack <= 1'b1;  rdata <= clock_since_acp_at_arp        [32-1: 0]; end
        `OFFSET_TrigAtARP                  : begin ack <= 1'b1;  rdata <= trig_at_arp                   [32-1: 0]; end
        `OFFSET_Clocks_LO                  : begin ack <= 1'b1;  rdata <= clocks                        [32-1: 0]; end
        `OFFSET_Clocks_HI                  : begin ack <= 1'b1;  rdata <= clocks                        [64-1:32]; end
        `OFFSET_ACPRaw                     : begin ack <= 1'b1;  rdata <= acp_raw                       [32-1: 0]; end
        `OFFSET_ARPRaw                     : begin ack <= 1'b1;  rdata <= arp_raw                       [32-1: 0]; end
        `OFFSET_saved_TrigClock_LO         : begin ack <= 1'b1;  rdata <= saved_trig_clock              [32-1: 0]; end
        `OFFSET_saved_TrigClock_HI         : begin ack <= 1'b1;  rdata <= saved_trig_clock              [64-1:32]; end
        `OFFSET_saved_TrigPrevClock_LO     : begin ack <= 1'b1;  rdata <= saved_trig_prev_clock         [32-1: 0]; end
        `OFFSET_saved_TrigPrevClock_HI     : begin ack <= 1'b1;  rdata <= saved_trig_prev_clock         [64-1:32]; end
        `OFFSET_saved_ACPClock_LO          : begin ack <= 1'b1;  rdata <= saved_acp_clock               [32-1: 0]; end
        `OFFSET_saved_ACPClock_HI          : begin ack <= 1'b1;  rdata <= saved_acp_clock               [64-1:32]; end
        `OFFSET_saved_ACPPrevClock_LO      : begin ack <= 1'b1;  rdata <= saved_acp_prev_clock          [32-1: 0]; end
        `OFFSET_saved_ACPPrevClock_HI      : begin ack <= 1'b1;  rdata <= saved_acp_prev_clock          [64-1:32]; end
        `OFFSET_saved_ARPClock_LO          : begin ack <= 1'b1;  rdata <= saved_arp_clock               [32-1: 0]; end
        `OFFSET_saved_ARPClock_HI          : begin ack <= 1'b1;  rdata <= saved_arp_clock               [64-1:32]; end
        `OFFSET_saved_ARPPrevClock_LO      : begin ack <= 1'b1;  rdata <= saved_arp_prev_clock          [32-1: 0]; end
        `OFFSET_saved_ARPPrevClock_HI      : begin ack <= 1'b1;  rdata <= saved_arp_prev_clock          [64-1:32]; end
        `OFFSET_saved_TrigCount            : begin ack <= 1'b1;  rdata <= saved_trig_count              [32-1: 0]; end
        `OFFSET_saved_ACPCount             : begin ack <= 1'b1;  rdata <= saved_acp_count               [32-1: 0]; end
        `OFFSET_saved_ARPCount             : begin ack <= 1'b1;  rdata <= saved_arp_count               [32-1: 0]; end
        `OFFSET_saved_ACPPerARP            : begin ack <= 1'b1;  rdata <= saved_acp_per_arp             [32-1: 0]; end
        `OFFSET_saved_ADCCounter           : begin ack <= 1'b1;  rdata <= saved_adc_counter             [32-1: 0]; end
        `OFFSET_saved_ACPAtARP             : begin ack <= 1'b1;  rdata <= saved_acp_at_arp              [32-1: 0]; end
        `OFFSET_saved_ClockSinceACPAtARP   : begin ack <= 1'b1;  rdata <= saved_clock_since_acp_at_arp  [32-1: 0]; end
        `OFFSET_saved_TrigAtARP            : begin ack <= 1'b1;  rdata <= saved_trig_at_arp             [32-1: 0]; end
